---
- hosts: all
  gather_facts: false
  roles:
  #- cloudalchemy.prometheus
  - prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - demo.cloudalchemy.org:9100
        labels:
          env: demosite